sonar.projectKey=sonarqube-github-actions-demo
sonar.projectName=SonarQube GitHub Actions Demo

sonar.sources=src
sonar.tests=tests

sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=**/__pycache__/**,**/.pytest_cache/**